### PR TITLE
fix: move validation status to the selected answer

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

The QuizQuestion validation status is currently displayed next to the question text, but it is currently having an alignment issue. #339 was created to address the issue, but we wanted to take this opportunity to revisit how the status should be communicated (because displaying the icon alone is too subtle).

This PR is an alternative, in which the validation status is moved into the selected answer, and the background of the selected answer is changed based on the validation status.

## Screenshot

<details>
  <summary>Before</summary>

  Screenshot 2024-09-26 at 02 51 18
</details>

<details>
  <summary>After</summary>

|  | Light | Dark |
| --- | --- | --- |
| Correct | Screenshot 2024-10-08 at 03 44 58 | Screenshot 2024-10-08 at 03 34 04 | 
| Incorrect | Screenshot 2024-10-08 at 03 44 50 | Screenshot 2024-10-08 at 03 34 11 |
</details>

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
The only thing that jumps out at me is that the height will change when you validate, which will make the page move around. Would it be better to communicate via colour and mouse-over/SR-only text instead?

**Review by ojeytonwilliams — APPROVED** [review]
Ah, I see. Tricky to avoid, then.

LGTM :+1:

**Comment by moT01** [comment]
I made this for now to render all the questions on the client: github.com/freeCodeCamp/freeCodeCamp/pull/56582

It should just be an intermediate step before moving to use this component. I think the UI I came up with is pretty decent (see images in PR description). One issue I had with changing the whole background is that if an option has a codeblock (triple backticks), then the codeblock still had the regular background and it didn't look great. Adding the background to only the feedback looks good enough - but still didn't seem right. Wondering if we should go with something like that PR does. I do think it aligns pretty good with some similar feedback we use on other challenges. The editor challenges for instance:

Screenshot 2024-10-08 at 8 57 50 AM

And the fill in the blank challenges:
 
Screenshot 2024-10-08 at 8 58 17 AM

**Review by moT01 — APPROVED** [review]
Alright, I was able to play with this. I think it's looking good - so I am going to merge it.

Screenshot 2024-10-08 at 3 11 35 PM

We can iterate on it if needed.

**Pull request merged**
