### PR TITLE
feat: add changelog file

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
IMHO, It doesn't work like that. For starters, the SemVer notation is incorrect, you want this to be automated with proper release management.

**Comment by Sembauke** [comment]
> IMHO, It doesn't work like that. For starters, the SemVer notation is incorrect, you want this to be automated with proper release management.

I hade no clue the change log could be automated. That is cool. It seems that I have not understood which version this should be.

**Comment by raisedadead** [comment]
No worries - The changeset tool helps with a lot of the concepts around release management. Consider taking some time to go through their concepts.

**Comment by Sembauke** [comment]
I will close this. Thanks for the tips :).

**Pull request closed without merging**
